# Config variables
RCC := /usr/lib/qt6/rcc
UIC := /usr/lib/qt6/uic
MOC := /usr/lib/qt6/moc
CXX := g++

TARGET := fastplayer
INSTALL_BIN_DIR := /usr/local/bin
ICONS := resources/fastplayer.svg
INSTALL_ICONS_DIR := /usr/share/icons/hicolor/scalable/apps
DESKTOP_FILE := resources/fastplayer.desktop
INSTALL_DESKTOP_FILE_DIR := /usr/share/applications

INCLUDE := \
	-I/usr/include/qt6 \
 	-I/usr/include/qt6/QtWidgets \
	-I/usr/include/qt6/QtOpenGLWidgets \
	-I/usr/include/qt6/QtCore \
	-I/usr/include/qt6/QtGui \
	-I/usr/include/mpv

LIBS := \
	-L/usr/lib/x86_64-linux-gnu \
	-lQt6Widgets \
	-lQt6Gui \
	-lQt6Core \
	-lQt6OpenGLWidgets \
	-lmpv

CXXFLAGS := \
	-std=c++17 \
	-Wall \
	-Wextra \
	-pedantic \
	-O2 \
	-fPIC # seems to be required for Qt6

# End Config

# NOTE: All .h files except those that are auto generated by this file
# are assigned to be processed by the MOC compiler (required for Qt's signals).
# When this is unneeded, it will generate an empty .cpp file, then a small .o file.
# You can ignore it, or use another extension such as .hpp or .hh to avoid this.

# Auto assigned variables:
H := $(filter-out $(wildcard ui_*.h), $(wildcard *.h))
QRC := $(wildcard *.qrc)
UI := $(wildcard *.ui)
CPP := $(sort $(wildcard *.cpp) $(H:%.h=moc_%.cpp) $(QRC:%.qrc=qrc_%.cpp))
OBJ := $(CPP:%.cpp=%.o)

.DEFAULT_GOAL := all
.PHONY: all ui debug run rebuild clean cleanobj install
.SECONDARY:

all: ui $(OBJ)
	@echo "make all"
	$(CXX) $(CXXFLAGS) $(INCLUDE) $(OBJ) -o $(TARGET) $(LIBS)

# generate UI header files
ui: $(UI:%.ui=ui_%.h)

# Check if it's built, not adding `all` as requirement to 
# avoid building as root as it is usually required when installing
install:
	@(test -f $(TARGET) && install --mode +x -D -t $(INSTALL_BIN_DIR) $(TARGET) && echo "Installed $(TARGET) to $(INSTALL_BIN_DIR)") || (echo "$(TARGET) not built yet, use 'make' to build." && exit 1)
ifneq ($(strip $(ICONS)),)
	$(foreach icon, $(ICONS), \
	@(test -f $(icon) && install -D -t $(INSTALL_ICONS_DIR) $(icon) && echo "Installed $(icon) to $(INSTALL_ICONS_DIR)") \
	)
endif
ifneq ($(strip $(DESKTOP_FILE)),)
	@(test -f $(DESKTOP_FILE) && install -D -t $(INSTALL_DESKTOP_FILE_DIR) $(DESKTOP_FILE) && echo "Installed $(DESKTOP_FILE) to $(INSTALL_DESKTOP_FILE_DIR)")
endif

run: all
	./$(TARGET)

rebuild: clean
rebuild: all

debug: CXXFLAGS += -DDEBUG -g
debug: all

cleanobj:
	-rm -vf *.o moc_*.cpp qrc_*.cpp ui_*.h
clean: cleanobj
	-rm -vf $(TARGET)

ui_%.h: %.ui
	@echo "- $^ > $@"
	$(UIC) $< -o $@

qrc_%.cpp : %.qrc
	@echo "- $^ > $@"
	$(RCC) $< -o $@

moc_%.cpp: %.h
	@echo "- $^ > $@"
	$(MOC) $< -o $@

%.o : %.cpp
	@echo "- $^ > $@"
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o $@ -c $<
